server:
  port: 10000

spring:
  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false

  application:
    name: friday-commerce-service

  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT:localhost}:3333/commerce?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useServerPrepStmts=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME:local}
    password: ${RDS_PASSWORD:local}

    hikari:
      pool-name: HikariPool-Dev
      maximum-pool-size: 10
      minimum-idle: 1
      leak-detection-threshold: 60000
      connection-timeout: 3000     # 3s  → 3,000 ms
      max-lifetime: 1800000        # 30m → 1,800,000 ms
      idle-timeout: 300000         # 5m  →   300,000 ms

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        show_sql: false
        jdbc.time_zone: Asia/Seoul
        generate_statistics: true
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 300
    open-in-view: false

  data:
    redis:
      # 기본 연결(Standalone)
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}     # 비번 없으면 빈 값
      database: ${REDIS_DATABASE:0}    # 논리 DB index
      client-type: lettuce             # 기본값(lettuce); jedis 쓰면 jedis로 변경
      client-name: ${spring.application.name}
      # 타임아웃 (Duration 문법)
      connect-timeout: 2s              # TCP 연결 타임아웃
      timeout: 2s                      # 커맨드 읽기/쓰기 타임아웃
      ssl:
        enabled: ${REDIS_SSL:false}

      # Lettuce 풀 설정(Commons Pool2)
      lettuce:
        pool:
          enabled: true
          max-active: 16
          max-idle: 8
          min-idle: 1
          max-wait: 2s

  jwt:
    secret-access: ${ACCESS_SECRET}
    secret-refresh: ${REFRESH_SECRET}
    access-token-expiration: ${ACCESS_TOKEN_EXPIRATION:36000000}
    refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION:86400000}

  mail:
    host: smtp.naver.com
    port: ${NAVER_MAIL_PORT}
    username: ${NAVER_ID}
    password: ${NAVER_PW}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
          connectionTimeout: ${TIMEOUT}
          timeout: ${TIMEOUT}
          writeTimeout: ${TIMEOUT}
        debug: true

management:
  health:
    redis:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans,env,configprops,threaddump,loggers
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: DEBUG
    org.hibernate.stat: DEBUG
    org.hibernate.SQL_SLOW: INFO
    org.springframework.data.redis: INFO
    io.lettuce.core: INFO

    org.springframework.jdbc.core: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: INFO
    com.zaxxer.hikari.HikariConfig: INFO
    com.zaxxer.hikari: DEBUG

snowflake:
  epoch-millis: ${SNOWFLAKE_EPOCH_MILLIS}             # 2025-09-22T00:00:00Z
  node-id: ${SNOWFLAKE_NODE_ID}                       # 각 인스턴스/노드별 고유 값 할당
  clock-skew-tolerance-millis: ${SNOWFLAKE_CLOCK_SKEW_TOLERANCE_MILLIS}  # 5~20 권장
  auto-detect-node-id: ${SNOWFLAKE_AUTO_DETECT_NODE_ID}       # 운영에선 명시 지정 권장


auth:
  email: # ← EmailVerificationProperties(@ConfigurationProperties) 바인딩
    code-validity-duration: 5m          # Duration 타입: 5분
    resend-cooldown-duration: 60s       # 재요청 쿨타임
    max-attempts: 5                     # 최대 인증 시도
    lockout-duration: 10m               # 시도 초과 차단 시간
    success-validity-duration: 10m      # 검증 성공 플래그 TTL


security:
  current-user:
    allow-header-fallback: false

  jwt:
    filter:
      default-path-pattern: REQUIRED
      exclude-path-patterns:
        - /actuator/**
        - /docs/**
      optional-path-patterns:
        - /users/**
      include-path-patterns:
        /api/**
