@baseUrl = http://localhost:10000

### @name SignUp_Success
# 정상 회원가입 시나리오
POST {{baseUrl}}/api/v1/auth/sign-up
Content-Type: application/json
Accept: application/json

{
  "email": "alice@example.com",
  "password": "Aa!23456",
  "username": "앨리스123",
  "agreement": {
    "termsOfService": true,
    "privacy": true,
    "marketing": true
  },
  "address": {
    "zipCode": "06236",
    "addressLine1": "서울시 강남구 테헤란로 123",
    "addressLine2": "OO빌딩 5층",
    "city": "서울",
    "state": "강남구"
  }
}

> {%
  client.global.set("addressId", response.body.userAddresses.addressId)
%}


### 로그인 성공 시나리오
POST http://localhost:10000/api/v1/auth/sign-in
Content-Type: application/json
Accept: application/json

{
  "email": "alice@example.com",
  "password": "Aa!23456"
}

> {%
  client.global.set("userId", response.body.userId.toFixed(0))
  client.global.set("at", response.body.at)
  client.global.set("rt", response.body.rt)
%}

### 주소 등록
POST http://localhost:10000/api/v1/users/addresses
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{at}}

{
  "zipCode": "12345",
  "addressLine1": "서울특별시 강남구 테헤란로 123",
  "addressLine2": "101동 202호",
  "city": "서울",
  "state": "강남구"
}

### 기본 주소 등록
POST http://localhost:10000/api/v1/users/addresses/2/default
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{at}}

{}


### 주소 삭제
DELETE http://localhost:10000/api/v1/users/addresses/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{at}}

{}

###

